In [29]:
import pandas as pd
import numpy as np

In [30]:
trainingData = pd.read_csv('Train.csv')
testingData = pd.read_csv('Test.csv')

length = np.array([trainingData["PetalLengthCm"]])
width = np.array([trainingData["PetalWidthCm"]])
Species = np.array([trainingData["Species"]])

labeledData = np.array([testingData["Species"]], dtype=object)
predicted_values=np.empty (labeledData.size, dtype=object)

In [31]:
x_tilda = np.concatenate((length.reshape(length.size,1), width.reshape(width.size,1), np.ones((length.size,1))), axis=1)

In [32]:
targetVersicolor = np.where(Species=='Iris-versicolor' , 1, -1).reshape(Species.size,1)
wVersicolor = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targetVersicolor
wVersicolor

array([[ 0.57079356],
       [-1.18057071],
       [-1.0433656 ]])

In [33]:
targetSetosa = np.where(Species=='Iris-setosa' , 1, -1).reshape(Species.size,1)
wSetosa = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targetSetosa
wSetosa

array([[-0.50070391],
       [ 0.03941776],
       [ 1.48011265]])

In [34]:
targetVirginica = np.where(Species=='Iris-virginica' , 1, -1).reshape(Species.size,1)
wVirginica = np.linalg.inv(x_tilda.T @ x_tilda) @ x_tilda.T @ targetVirginica
wVirginica

array([[-0.07008965],
       [ 1.14115295],
       [-1.43674706]])

In [35]:
def Setosa(l,w):
    return l*(-0.50070391)+w*(0.03941776)+1.48011265

In [36]:
def Versicolor(l,w):
    return l*(0.57079356)-w*(1.18057071)-1.0433656

In [37]:
def Virginica(l,w):
    return l*(-0.07008965)+w*(1.14115295)-1.43674706

In [38]:
for i in range(0, labeledData.size):
    petalLength=testingData.loc[i]["PetalLengthCm"]
    petalWidth=testingData.loc[i]["PetalWidthCm"]

    setosa = Setosa(petalLength,petalWidth)
    versicolor = Versicolor(petalLength,petalWidth)
    virginica = Virginica(petalLength,petalWidth)

    if(versicolor>setosa):
         if(versicolor>virginica):
             predicted_values[i]="Iris-versicolor"
         else:
             predicted_values[i]="Iris-virginica"
    else:
         if(setosa>virginica):
             predicted_values[i]="Iris-setosa"
         else:
             predicted_values[i]="Iris-virginica"  

predicted_values

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [39]:
def ConfusionMatrix(actual, predicted):
    classes = np.unique(labeledData)
    conf = np.zeros((len(classes), len(classes)))

    for i in range(len(classes)):
        for j in range(len(classes)):
            conf[i, j] = np.sum((actual == classes[i]) & (predicted == classes[j]))
    return conf

print(ConfusionMatrix(labeledData, predicted_values))

[[19.  0.  0.]
 [ 0.  5.  8.]
 [ 0.  0. 13.]]


In [40]:
setosaCorrectlyPredicted = 19
viginicaCorrectlyPredicted = 13
versicolorCorrectlyPredicted = 5
versicolorFalselyPredictedAVirginica=8
setosaTotal = 19
virginicaTotal = 13 
versicolorTotal = 13
accuracy = (setosaCorrectlyPredicted + viginicaCorrectlyPredicted + versicolorCorrectlyPredicted)/(setosaTotal+virginicaTotal+versicolorTotal)
accuracy*100

82.22222222222221